import type { Option } from 'payload'

/** All UN member states + major territories — sorted alphabetically by name.
 *  Value is the flag emoji; label is "🏳 Country Name" for easy search. */
export const COUNTRY_FLAGS: Option[] = [
  { label: '🇦🇫 Afghanistan', value: '🇦🇫' },
  { label: '🇦🇱 Albania', value: '🇦🇱' },
  { label: '🇩🇿 Algeria', value: '🇩🇿' },
  { label: '🇦🇩 Andorra', value: '🇦🇩' },
  { label: '🇦🇴 Angola', value: '🇦🇴' },
  { label: '🇦🇬 Antigua and Barbuda', value: '🇦🇬' },
  { label: '🇦🇷 Argentina', value: '🇦🇷' },
  { label: '🇦🇲 Armenia', value: '🇦🇲' },
  { label: '🇦🇼 Aruba', value: '🇦🇼' },
  { label: '🇦🇺 Australia', value: '🇦🇺' },
  { label: '🇦🇹 Austria', value: '🇦🇹' },
  { label: '🇦🇿 Azerbaijan', value: '🇦🇿' },
  { label: '🇧🇸 Bahamas', value: '🇧🇸' },
  { label: '🇧🇭 Bahrain', value: '🇧🇭' },
  { label: '🇧🇩 Bangladesh', value: '🇧🇩' },
  { label: '🇧🇧 Barbados', value: '🇧🇧' },
  { label: '🇧🇾 Belarus', value: '🇧🇾' },
  { label: '🇧🇪 Belgium', value: '🇧🇪' },
  { label: '🇧🇿 Belize', value: '🇧🇿' },
  { label: '🇧🇯 Benin', value: '🇧🇯' },
  { label: '🇧🇹 Bhutan', value: '🇧🇹' },
  { label: '🇧🇴 Bolivia', value: '🇧🇴' },
  { label: '🇧🇦 Bosnia and Herzegovina', value: '🇧🇦' },
  { label: '🇧🇼 Botswana', value: '🇧🇼' },
  { label: '🇧🇷 Brazil', value: '🇧🇷' },
  { label: '🇧🇳 Brunei', value: '🇧🇳' },
  { label: '🇧🇬 Bulgaria', value: '🇧🇬' },
  { label: '🇧🇫 Burkina Faso', value: '🇧🇫' },
  { label: '🇧🇮 Burundi', value: '🇧🇮' },
  { label: '🇨🇻 Cabo Verde', value: '🇨🇻' },
  { label: '🇰🇭 Cambodia', value: '🇰🇭' },
  { label: '🇨🇲 Cameroon', value: '🇨🇲' },
  { label: '🇨🇦 Canada', value: '🇨🇦' },
  { label: '🇨🇫 Central African Republic', value: '🇨🇫' },
  { label: '🇹🇩 Chad', value: '🇹🇩' },
  { label: '🇨🇱 Chile', value: '🇨🇱' },
  { label: '🇨🇳 China', value: '🇨🇳' },
  { label: '🇨🇴 Colombia', value: '🇨🇴' },
  { label: '🇰🇲 Comoros', value: '🇰🇲' },
  { label: '🇨🇩 Congo (DRC)', value: '🇨🇩' },
  { label: '🇨🇬 Congo (Republic)', value: '🇨🇬' },
  { label: '🇨🇷 Costa Rica', value: '🇨🇷' },
  { label: '🇭🇷 Croatia', value: '🇭🇷' },
  { label: '🇨🇺 Cuba', value: '🇨🇺' },
  { label: '🇨🇾 Cyprus', value: '🇨🇾' },
  { label: '🇨🇿 Czechia', value: '🇨🇿' },
  { label: '🇩🇰 Denmark', value: '🇩🇰' },
  { label: '🇩🇯 Djibouti', value: '🇩🇯' },
  { label: '🇩🇲 Dominica', value: '🇩🇲' },
  { label: '🇩🇴 Dominican Republic', value: '🇩🇴' },
  { label: '🇪🇨 Ecuador', value: '🇪🇨' },
  { label: '🇪🇬 Egypt', value: '🇪🇬' },
  { label: '🇸🇻 El Salvador', value: '🇸🇻' },
  { label: '🇬🇶 Equatorial Guinea', value: '🇬🇶' },
  { label: '🇪🇷 Eritrea', value: '🇪🇷' },
  { label: '🇪🇪 Estonia', value: '🇪🇪' },
  { label: '🇸🇿 Eswatini', value: '🇸🇿' },
  { label: '🇪🇹 Ethiopia', value: '🇪🇹' },
  { label: '🇫🇯 Fiji', value: '🇫🇯' },
  { label: '🇫🇮 Finland', value: '🇫🇮' },
  { label: '🇫🇷 France', value: '🇫🇷' },
  { label: '🇬🇦 Gabon', value: '🇬🇦' },
  { label: '🇬🇲 Gambia', value: '🇬🇲' },
  { label: '🇬🇪 Georgia', value: '🇬🇪' },
  { label: '🇩🇪 Germany', value: '🇩🇪' },
  { label: '🇬🇭 Ghana', value: '🇬🇭' },
  { label: '🇬🇮 Gibraltar', value: '🇬🇮' },
  { label: '🇬🇷 Greece', value: '🇬🇷' },
  { label: '🇬🇩 Grenada', value: '🇬🇩' },
  { label: '🇬🇹 Guatemala', value: '🇬🇹' },
  { label: '🇬🇺 Guam', value: '🇬🇺' },
  { label: '🇬🇳 Guinea', value: '🇬🇳' },
  { label: '🇬🇼 Guinea-Bissau', value: '🇬🇼' },
  { label: '🇬🇾 Guyana', value: '🇬🇾' },
  { label: '🇭🇹 Haiti', value: '🇭🇹' },
  { label: '🇭🇳 Honduras', value: '🇭🇳' },
  { label: '🇭🇰 Hong Kong', value: '🇭🇰' },
  { label: '🇭🇺 Hungary', value: '🇭🇺' },
  { label: '🇮🇸 Iceland', value: '🇮🇸' },
  { label: '🇮🇳 India', value: '🇮🇳' },
  { label: '🇮🇩 Indonesia', value: '🇮🇩' },
  { label: '🇮🇷 Iran', value: '🇮🇷' },
  { label: '🇮🇶 Iraq', value: '🇮🇶' },
  { label: '🇮🇪 Ireland', value: '🇮🇪' },
  { label: '🇮🇱 Israel', value: '🇮🇱' },
  { label: '🇮🇹 Italy', value: '🇮🇹' },
  { label: '🇯🇲 Jamaica', value: '🇯🇲' },
  { label: '🇯🇵 Japan', value: '🇯🇵' },
  { label: '🇯🇴 Jordan', value: '🇯🇴' },
  { label: '🇰🇿 Kazakhstan', value: '🇰🇿' },
  { label: '🇰🇪 Kenya', value: '🇰🇪' },
  { label: '🇰🇮 Kiribati', value: '🇰🇮' },
  { label: '🇽🇰 Kosovo', value: '🇽🇰' },
  { label: '🇰🇼 Kuwait', value: '🇰🇼' },
  { label: '🇰🇬 Kyrgyzstan', value: '🇰🇬' },
  { label: '🇱🇦 Laos', value: '🇱🇦' },
  { label: '🇱🇻 Latvia', value: '🇱🇻' },
  { label: '🇱🇧 Lebanon', value: '🇱🇧' },
  { label: '🇱🇸 Lesotho', value: '🇱🇸' },
  { label: '🇱🇷 Liberia', value: '🇱🇷' },
  { label: '🇱🇾 Libya', value: '🇱🇾' },
  { label: '🇱🇮 Liechtenstein', value: '🇱🇮' },
  { label: '🇱🇹 Lithuania', value: '🇱🇹' },
  { label: '🇱🇺 Luxembourg', value: '🇱🇺' },
  { label: '🇲🇴 Macao', value: '🇲🇴' },
  { label: '🇲🇬 Madagascar', value: '🇲🇬' },
  { label: '🇲🇼 Malawi', value: '🇲🇼' },
  { label: '🇲🇾 Malaysia', value: '🇲🇾' },
  { label: '🇲🇻 Maldives', value: '🇲🇻' },
  { label: '🇲🇱 Mali', value: '🇲🇱' },
  { label: '🇲🇹 Malta', value: '🇲🇹' },
  { label: '🇲🇭 Marshall Islands', value: '🇲🇭' },
  { label: '🇲🇷 Mauritania', value: '🇲🇷' },
  { label: '🇲🇺 Mauritius', value: '🇲🇺' },
  { label: '🇲🇽 Mexico', value: '🇲🇽' },
  { label: '🇫🇲 Micronesia', value: '🇫🇲' },
  { label: '🇲🇩 Moldova', value: '🇲🇩' },
  { label: '🇲🇨 Monaco', value: '🇲🇨' },
  { label: '🇲🇳 Mongolia', value: '🇲🇳' },
  { label: '🇲🇪 Montenegro', value: '🇲🇪' },
  { label: '🇲🇦 Morocco', value: '🇲🇦' },
  { label: '🇲🇿 Mozambique', value: '🇲🇿' },
  { label: '🇲🇲 Myanmar', value: '🇲🇲' },
  { label: '🇳🇦 Namibia', value: '🇳🇦' },
  { label: '🇳🇷 Nauru', value: '🇳🇷' },
  { label: '🇳🇵 Nepal', value: '🇳🇵' },
  { label: '🇳🇱 Netherlands', value: '🇳🇱' },
  { label: '🇳🇿 New Zealand', value: '🇳🇿' },
  { label: '🇳🇮 Nicaragua', value: '🇳🇮' },
  { label: '🇳🇪 Niger', value: '🇳🇪' },
  { label: '🇳🇬 Nigeria', value: '🇳🇬' },
  { label: '🇲🇰 North Macedonia', value: '🇲🇰' },
  { label: '🇰🇵 North Korea', value: '🇰🇵' },
  { label: '🇳🇴 Norway', value: '🇳🇴' },
  { label: '🇴🇲 Oman', value: '🇴🇲' },
  { label: '🇵🇰 Pakistan', value: '🇵🇰' },
  { label: '🇵🇼 Palau', value: '🇵🇼' },
  { label: '🇵🇸 Palestine', value: '🇵🇸' },
  { label: '🇵🇦 Panama', value: '🇵🇦' },
  { label: '🇵🇬 Papua New Guinea', value: '🇵🇬' },
  { label: '🇵🇾 Paraguay', value: '🇵🇾' },
  { label: '🇵🇪 Peru', value: '🇵🇪' },
  { label: '🇵🇭 Philippines', value: '🇵🇭' },
  { label: '🇵🇱 Poland', value: '🇵🇱' },
  { label: '🇵🇹 Portugal', value: '🇵🇹' },
  { label: '🇵🇷 Puerto Rico', value: '🇵🇷' },
  { label: '🇶🇦 Qatar', value: '🇶🇦' },
  { label: '🇷🇴 Romania', value: '🇷🇴' },
  { label: '🇷🇺 Russia', value: '🇷🇺' },
  { label: '🇷🇼 Rwanda', value: '🇷🇼' },
  { label: '🇰🇳 Saint Kitts and Nevis', value: '🇰🇳' },
  { label: '🇱🇨 Saint Lucia', value: '🇱🇨' },
  { label: '🇻🇨 Saint Vincent and the Grenadines', value: '🇻🇨' },
  { label: '🇼🇸 Samoa', value: '🇼🇸' },
  { label: '🇸🇲 San Marino', value: '🇸🇲' },
  { label: '🇸🇹 São Tomé and Príncipe', value: '🇸🇹' },
  { label: '🇸🇦 Saudi Arabia', value: '🇸🇦' },
  { label: '🇸🇳 Senegal', value: '🇸🇳' },
  { label: '🇷🇸 Serbia', value: '🇷🇸' },
  { label: '🇸🇨 Seychelles', value: '🇸🇨' },
  { label: '🇸🇱 Sierra Leone', value: '🇸🇱' },
  { label: '🇸🇬 Singapore', value: '🇸🇬' },
  { label: '🇸🇰 Slovakia', value: '🇸🇰' },
  { label: '🇸🇮 Slovenia', value: '🇸🇮' },
  { label: '🇸🇧 Solomon Islands', value: '🇸🇧' },
  { label: '🇸🇴 Somalia', value: '🇸🇴' },
  { label: '🇿🇦 South Africa', value: '🇿🇦' },
  { label: '🇰🇷 South Korea', value: '🇰🇷' },
  { label: '🇸🇸 South Sudan', value: '🇸🇸' },
  { label: '🇪🇸 Spain', value: '🇪🇸' },
  { label: '🇱🇰 Sri Lanka', value: '🇱🇰' },
  { label: '🇸🇩 Sudan', value: '🇸🇩' },
  { label: '🇸🇷 Suriname', value: '🇸🇷' },
  { label: '🇸🇪 Sweden', value: '🇸🇪' },
  { label: '🇨🇭 Switzerland', value: '🇨🇭' },
  { label: '🇸🇾 Syria', value: '🇸🇾' },
  { label: '🇹🇼 Taiwan', value: '🇹🇼' },
  { label: '🇹🇯 Tajikistan', value: '🇹🇯' },
  { label: '🇹🇿 Tanzania', value: '🇹🇿' },
  { label: '🇹🇭 Thailand', value: '🇹🇭' },
  { label: '🇹🇱 Timor-Leste', value: '🇹🇱' },
  { label: '🇹🇬 Togo', value: '🇹🇬' },
  { label: '🇹🇴 Tonga', value: '🇹🇴' },
  { label: '🇹🇹 Trinidad and Tobago', value: '🇹🇹' },
  { label: '🇹🇳 Tunisia', value: '🇹🇳' },
  { label: '🇹🇷 Türkiye', value: '🇹🇷' },
  { label: '🇹🇲 Turkmenistan', value: '🇹🇲' },
  { label: '🇹🇻 Tuvalu', value: '🇹🇻' },
  { label: '🇺🇬 Uganda', value: '🇺🇬' },
  { label: '🇺🇦 Ukraine', value: '🇺🇦' },
  { label: '🇦🇪 United Arab Emirates', value: '🇦🇪' },
  { label: '🇬🇧 United Kingdom', value: '🇬🇧' },
  { label: '🇺🇸 United States', value: '🇺🇸' },
  { label: '🇺🇾 Uruguay', value: '🇺🇾' },
  { label: '🇺🇿 Uzbekistan', value: '🇺🇿' },
  { label: '🇻🇺 Vanuatu', value: '🇻🇺' },
  { label: '🇻🇦 Vatican City', value: '🇻🇦' },
  { label: '🇻🇪 Venezuela', value: '🇻🇪' },
  { label: '🇻🇳 Vietnam', value: '🇻🇳' },
  { label: '🇾🇪 Yemen', value: '🇾🇪' },
  { label: '🇿🇲 Zambia', value: '🇿🇲' },
  { label: '🇿🇼 Zimbabwe', value: '🇿🇼' },
]
